name: Custom mod_harbour.v2.1 for Windows 64 

on:
  workflow_dispatch:
    inputs:
      ADS:
        type: boolean
        description: Include ADS
      LETODB:
        type: boolean
        description: Include LETODB
      MONGODB:
        type: boolean
        description: Include MONGODB
      TDOLPHIN:
        type: boolean
        description: Include TDOLPHIN
jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Checkout harbour/core repo
        uses: actions/checkout@v2
        with:
          repository: harbour/core
          path: harbour
  
      - name: Updating Harbour hbssl for new OpenSSL 
        run: |
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbp) -replace 'libeay32','libcrypto-1_1-x64' | Set-Content -path harbour\contrib\hbssl\hbssl.hbp
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbp) -replace 'ssleay32','libssl-1_1-x64' | Set-Content -path harbour\contrib\hbssl\hbssl.hbp
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbc) -replace 'libeay32','libcrypto-1_1-x64' | Set-Content -path harbour\contrib\hbssl\hbssl.hbc
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbc) -replace 'ssleay32','libssl-1_1-x64' | Set-Content -path harbour\contrib\hbssl\hbssl.hbc
         
      - name: Download and extract Harbour/Apache24 binaries
        shell: cmd      
        run: |
          curl -OL https://raw.githubusercontent.com/diegofazio/harbour_binaries/master/Windows/harbour_windows_64.zip
          7z x -y harbour_windows_64.zip -oharbour
          curl -OL https://raw.githubusercontent.com/diegofazio/harbour_binaries/master/apache24/win64.zip
          7z x -y win64.zip -oc:\Apache24

      - name: Checkout mod_harbour.v2 repo
        uses: actions/checkout@v2
        with:
          repository: mod-harbour/mod_harbour.v2
          path: harbour/contrib/mod_harbour.v2

      - name: Include ADS
        if: github.event.inputs.ADS == 'true'
        shell: cmd  
        run: |
          curl -OL https://raw.githubusercontent.com/diegofazio/harbour_binaries/master/ads64/acesdk-x64.zip
          7z x -y acesdk-x64.zip -oc:\acesdk

      - name: Build mod_harbour.v2.1
        working-directory: harbour/contrib/mod_harbour.v2
        shell: cmd
        run: |
          if "${{ github.event.inputs.ADS }}" == "true" (set ADS=-DHB_WITH_ADS=c:\acesdk rddads.hbc)
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          ..\..\bin\win\msvc64\hbmk2 mod_harbour.v2.1.hbp -comp=msvc64 -Lc:\Apache24\lib -Ic:\Apache24\include %ADS%

      - name: Extract MODVERSION and create artifact folder
        id: generate-name
        run: |
          mkdir artifact
          mkdir artifact\Samples
          $MODVERSION = findstr /C:"#define MODVERSION" harbour\contrib\mod_harbour.v2\source\main.prg
          $MODVERSION = $MODVERSION.Replace("#define MODVERSION","")
          $MODVERSION = $MODVERSION.Replace("'","")
          $MODVERSION = $MODVERSION.Trim()
          echo "::set-output name=modversion::$MODVERSION"  
          echo Mod-harbour.v2.1-Ver:$MODVERSION >>.\artifact\notes.txt

      - name: Check if custom
        id: generate-custom
        if: github.event.inputs.ADS == 'true' || github.event.inputs.LETODB == 'true'
        run: echo "::set-output name=custom::custom"  

      - name: Prepare artifact
        shell: cmd        
        run: |
          xcopy harbour\contrib\mod_harbour.v2\Samples\*.* .\artifact\Samples /E /H /C /I
          xcopy harbour\contrib\mod_harbour.v2\output\win64\mod_harbour.v2.so .\artifact /E /H /C /I
          xcopy harbour\contrib\mod_harbour.v2\output\win64\libmhapache.dll .\artifact /E /H /C /I
          if "${{ github.event.inputs.ADS }}" == "true" ( mkdir artifact\ads | xcopy c:\acesdk\*.dll .\artifact\ads /E /H /C /I | echo Include rddads >> .\artifact\notes.txt )
                   
      - name: Upload mod_harbour.v2.so/libmhapache.dll/Samples to artifact
        uses: actions/upload-artifact@v2
        with:
          name: mod_harbour.V${{ steps.generate-name.outputs.modversion }}_${{ steps.generate-custom.outputs.custom }}_win64
          path: artifact

   

