name: Mod-harbour.v2 Customizable Build

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: OS
        options: 
        - Win32
        - Win64
        - Ubuntu64
        - MacOS
      ADS:
        type: boolean
        description: Include ADS
      LETODB:
        type: boolean
        description: Include LETODB
      MONGODB:
        type: boolean
        description: Include MONGODB
